name: Github Action to keep workflow alive
on:
  workflow_dispatch:

jobs:
  prevent-workflow-disable:
    name: Prevent workflow disable
    runs-on: ubuntu-latest
    steps:
        - uses: gautamkrishnar/keepalive-workflow@v1
