name: Github Action to keep workflow alive
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  prevent-workflow-disable:
    name: Prevent workflow disable
    runs-on: ubuntu-latest
    steps:
        - uses: gautamkrishnar/keepalive-workflow@v1
